/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    events: Event;
    participants: Participant;
    registrations: Registration;
    newsletters: Newsletter;
    'newsletter-subscriptions': NewsletterSubscription;
    testimonials: Testimonial;
    pages: Page;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    'newsletter-subscriptions': NewsletterSubscriptionsSelect<false> | NewsletterSubscriptionsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Benutzer & Zugriffe
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Verwalte Events und Termine für den Männerkreis
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Wird für die URL verwendet: /events/[slug]
   */
  slug: string;
  description: string;
  image?: (number | null) | Media;
  eventDate: string;
  startTime: string;
  endTime: string;
  location: string;
  street?: string | null;
  zip?: string | null;
  city?: string | null;
  /**
   * Maximale Anzahl an Teilnehmern für dieses Event
   */
  maxParticipants: number;
  costBasis?: string | null;
  /**
   * Event auf der Website sichtbar machen
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bilder und Dateien
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Teilnehmer-Stammdaten
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Event-Anmeldungen verwalten
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  event: number | Event;
  participant: number | Participant;
  status: 'confirmed' | 'cancelled';
  note?: string | null;
  consentTimestamp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kampagnen erstellen und versenden
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  /**
   * Der Betreff der E-Mail
   */
  subject: string;
  /**
   * Optional: Wird in vielen E-Mail-Clients als Vorschau angezeigt
   */
  preheader?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Status wird automatisch aktualisiert
   */
  status: 'draft' | 'sending' | 'sent';
  sentAt?: string | null;
  /**
   * Anzahl der Empfänger beim Versand
   */
  recipientsCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Abonnenten verwalten
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions".
 */
export interface NewsletterSubscription {
  id: number;
  participant: number | Participant;
  status: 'pending' | 'confirmed' | 'unsubscribed';
  token?: string | null;
  confirmToken?: string | null;
  requestedAt?: string | null;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Erfahrungsberichte moderieren
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  content: string;
  /**
   * Optional - kann auch anonym bleiben
   */
  authorName?: string | null;
  authorRole?: string | null;
  /**
   * Nur für Rückfragen, wird nicht öffentlich angezeigt.
   */
  email: string;
  published?: boolean | null;
  publishedAt?: string | null;
  /**
   * Kleinere Zahlen erscheinen zuerst
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Seiten verwalten
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Wird für die URL verwendet: /[slug]
   */
  slug: string;
  content?:
    | (
        | {
            label?: string | null;
            title: string;
            description?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            text: string;
            image?: (number | null) | Media;
            quote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            items?:
              | {
                  number?: string | null;
                  title: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'valueItems';
          }
        | {
            name: string;
            role?: string | null;
            bio: string;
            quote?: string | null;
            photo?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'moderator';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            steps?:
              | {
                  number?: string | null;
                  title: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'journeySteps';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            eyebrow?: string | null;
            title: string;
            text?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            title?: string | null;
            text?: string | null;
            link?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'whatsappCommunity';
          }
      )[]
    | null;
  meta?: {
    /**
     * Falls leer, wird der Seitentitel verwendet
     */
    metaTitle?: string | null;
    /**
     * Empfohlen: 150-160 Zeichen
     */
    metaDescription?: string | null;
    /**
     * Bild für Facebook, Twitter, etc.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Seite auf der Website sichtbar machen
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'newsletter-subscriptions';
        value: number | NewsletterSubscription;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  eventDate?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  street?: T;
  zip?: T;
  city?: T;
  maxParticipants?: T;
  costBasis?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  event?: T;
  participant?: T;
  status?: T;
  note?: T;
  consentTimestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  subject?: T;
  preheader?: T;
  content?: T;
  status?: T;
  sentAt?: T;
  recipientsCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions_select".
 */
export interface NewsletterSubscriptionsSelect<T extends boolean = true> {
  participant?: T;
  status?: T;
  token?: T;
  confirmToken?: T;
  requestedAt?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  content?: T;
  authorName?: T;
  authorRole?: T;
  email?: T;
  published?: T;
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              ctaText?: T;
              ctaLink?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        intro?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              image?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        valueItems?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        moderator?:
          | T
          | {
              name?: T;
              role?: T;
              bio?: T;
              quote?: T;
              photo?: T;
              id?: T;
              blockName?: T;
            };
        journeySteps?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        whatsappCommunity?:
          | T
          | {
              title?: T;
              text?: T;
              link?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Allgemeine Website-Einstellungen
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  footerText?: string | null;
  socialLinks?:
    | {
        platform: 'email' | 'phone' | 'instagram' | 'facebook' | 'whatsapp' | 'website';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  homepage?: (number | null) | Page;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  contactPhone?: T;
  footerText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  homepage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}